### ISSUE TITLE
Crashed

### ISSUE THREAD

**Issue by Arthur-The-Ok** [Schaf-Unschaf/BountiesExpanded#17]
2003129 [Thread-3] ERROR com.fs.starfarer.combat.CombatMain  - java.lang.ClassCastException: java.lang.String cannot be cast to de.schafunschaf.bountiesexpanded.scripts.campaign.intel.bounties.highvaluebounty.HighValueBountyEntity
java.lang.ClassCastException: java.lang.String cannot be cast to de.schafunschaf.bountiesexpanded.scripts.campaign.intel.bounties.highvaluebounty.HighValueBountyEntity
	at de.schafunschaf.bountiesexpanded.scripts.campaign.intel.bounties.highvaluebounty.HighValueBountyManager.upgradeShips(HighValueBountyManager.java:205)
	at de.schafunschaf.bountiesexpanded.plugins.BountiesExpandedPlugin.reloadHVBSMods(BountiesExpandedPlugin.java:133)
	at de.schafunschaf.bountiesexpanded.plugins.BountiesExpandedPlugin.reloadSMods(BountiesExpandedPlugin.java:111)
	at de.schafunschaf.bountiesexpanded.plugins.BountiesExpandedPlugin.onGameLoad(BountiesExpandedPlugin.java:55)
	at com.fs.starfarer.campaign.save.CampaignGameManager.o00000(Unknown Source)
	at com.fs.starfarer.campaign.save.CampaignGameManager.o00000(Unknown Source)
	at com.fs.starfarer.title.TitleScreenState.menuItemSelected(Unknown Source)
	at com.fs.starfarer.title.Object.actionPerformed(Unknown Source)
	at com.fs.starfarer.ui.newnew.buttonPressed(Unknown Source)
	at com.fs.starfarer.ui.I.Ò00000(Unknown Source)
	at com.fs.starfarer.ui.I.processInput(Unknown Source)
	at com.fs.starfarer.ui.Stringsuper.super(Unknown Source)
	at com.fs.starfarer.BaseGameState.traverse(Unknown Source)
	at com.fs.state.AppDriver.begin(Unknown Source)
	at com.fs.starfarer.combat.CombatMain.main(Unknown Source)
	at com.fs.starfarer.StarfarerLauncher.o00000(Unknown Source)
	at com.fs.starfarer.StarfarerLauncher$1.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)

**Comment by Schaf-Unschaf** [comment]
Didn't get a notification about that issue..
That was fixed a few patches ago. I don't think you are still waiting for a fix, do you?
